export default {
    DailyEnchantItem: "dailyEnchantItem",
    DailyLevelUpItem: "dailyLevelUpItem",
    DailyBoostBeast: "dailyBoostBeast",
    DailySpendGold: "dailySpendGold",
    DailyDisenchant: "dailyDisenchant",
    DailyFreeRaid: "dailyFreeRaid",
    DailyPaidRaid: "dailyPaidRaid",
    DailyTower: "dailyTower",
    DailyBasicSummon: "dailyBasicSummon",
    DailyAdvancedSummon: "dailyAdvancedSummon",
    DailySilverChest: "dailySilverChest",
    DailyLegendaryChest: "dailyLegendaryChest",
    DailyLevelUpTroop: "dailyLevelUpTroop",
    DailyLevelUpGeneral: "dailyLevelUpGeneral",
    DailyArmourTrial: "dailyArmourTrial",
    DailyWeaponTrial: "dailyWeaponTrial",
    DailyAccessoryTrial: "dailyAccessoryTrial",
    DailyEngageQuest: "dailyEngageQuest",
    DailySpendPremium: "dailySpendPremium",
    DailyStartAdventure: "dailyStartAdventure",
    DailyAllTasks: "dailyAllTasks",
    DailyAllTasks2: "dailyAllTasks2",
    DailyAllTasks3: "dailyAllTasks3",
    DailySpendEnergy: "dailySpendEnergy"
};
