export default {
    NoHealth: "not enough health",
    NoStamina: "not enough stamina",
    NoEnergy: "not enough energy",
    NoItem: "no such item",
    NoMaterial: "no such material",
    NoTemplate: "no template for item",
    IncompatibleLevelingMaterial: "incompatible leveling material",
    IncorrectArguments: "incorrect arguments",
    ItemMaxLevel: "item at max level",
    NoRecipe: "no such recipe",
    NoRecipeIngridients: "not enough ingridients",
    NotEnoughCurrency: "not enough currency",
    PaymentIsPending: "payment is pending",
    BossDead: "boss is dead",
    BossIsLocked: "boss is locked",
    InvalidRaid: "invalid raid",
    RaidIsFull: "raid is full",
    NotConsumable: "not a consumable",
    UknownChest: "uknown chest",
    NoChestKey: "no chest key",
    UknownIAP: "unknown iap",
    MaxEnchantLevel: "max enchantement is reached",
    EnchantingInProcess: "enchanting in process",
    UnknownAdventure: "unknown adventure",
    AdventureInProcess: "adventure in process",
    AdventureClaimed: "adventure is claimed",
    AdventureWasRefreshed: "adventure already refreshed",
    CantChooseClass: "no class to choose",
    UnknownClass: "unknown class"
}