export default {
    NoHealth: "not enough health",
    NoStamina: "not enough stamina",
    NoEnergy: "not enough energy",
    NoItem: "no such item",
    NoEnoughItems: "not enough items",
    NoMaterial: "no such material",
    NotEnoughMaterial: "not enough material",
    NoTemplate: "no template for item",
    IncompatibleLevelingMaterial: "incompatible leveling material",
    IncorrectArguments: "incorrect arguments",
    ItemMaxLevel: "item at max level",
    NoRecipe: "no such recipe",
    NoRecipeIngridients: "not enough ingridients",
    NotEnoughCurrency: "not enough currency",
    NotEnoughSoft: "not enough soft currency",
    PaymentIsPending: "payment is pending",
    BossDead: "boss is dead",
    BossIsLocked: "boss is locked",
    InvalidRaid: "invalid raid",
    RaidIsFull: "raid is full",
    NotConsumable: "not a consumable",
    UknownChest: "uknown chest",
    NoChestKey: "no chest key",
    UknownIAP: "unknown iap",
    MaxEnchantLevel: "max enchantement is reached",
    EnchantingInProcess: "enchanting in process",
    ItemNotEnchantable: "item is not enchantable",
    UnknownAdventure: "unknown adventure",
    AdventureInProcess: "adventure in process",
    AdventureClaimed: "adventure is claimed",
    AdventureWasRefreshed: "adventure already refreshed",
    CantChooseClass: "no class to choose",
    UnknownClass: "unknown class",
    DailyRewardCollected: "daily reward collected",
    DailyRefillCollected: "daily refills collected",
    BeastMaxLevel: "beast at max level",
    BeastCantEvolve: "cant evolve beast",
    UknownPaymentId: "unknown payment id",
    NotEnoughResource: "not enough resource",
    TowerFloorInProcess: "tower floor not finished",
    TowerNoTicket: "no ticket",
    TowerFloorClaimed: "tower floor claimed",
    TowerFloorFinished: "tower floor finished",
    UnknownTrialType: "unknown trial type",
    UnknownTrial: "unknown trial",
    UnknownTrialStage: "unknown trial stage",
    UnknownTrialFight: "unknown trial fight",
    TrialClearPreviousStages: "clear previous stages",
    TrialFinishPreviousFights: "finish previous fights",
    TrialFightFinished: "fight is finished",
    TrialStageCleared: "stage is cleared",
    TrialInFight:"in fight",
    TrialNotInFight: "not in fight",
    TrialNoAttempts: "no attempts",
    TrialNoCards: "no cards to choose from",
    TrialInvalidCard: "invalid card",
    TrialStageRewardCollected: "stage reward is collected",
    TrialStageNotCleared: "stage is not cleared",
    TrialCardMaxLevel: "card max level",
    TrialNotEnoughPoints: "not enough trial points",
    TrialsNotEnoughMana: "not enough mana",
    GoldExchangeNoFreeBoosts: "gold exchange no free boosts",
    GoldExchangeNoFreeChanges: "gold exchange no free changes",
    DailyQuestsCantRefresh: "cant refresh daily quests",
    DailyQuestsTaskCompleted: "daily task completed",
    DividendsWithdrawalPending: "div token withdrawal in process",
    NoDividendsWithdrawal: "no pending withdrawals",
    NoSuchTournament: "no_such_tournament",
    PlayerNotRanked: "player_not_ranked",
    NotInTournament: "not_in_tournament",
    NoRewards: "no_rewards",
    NotInRace: "not_in_race",
    NoSuchRace: "no_such_race",
    UnknownLot: "unknown lot",
    CantJoinRace: "can't join race",
    ArmyNoUnit: "no such unit",
    ArmyUnitUnknown: "unknown unit",
    UnexpectedArmyUnit: "unexpected unit",
    ArmyUnitMaxLvl: "unit is at max level",
    NotEnoughEssence: "not enough essence",
    ItemEquipped: "item already equipped",
    NotEquipment: "not equipment"
}
