module.exports = {
    ExperienceChanged: "exp-changed",
    InventoryUpdate: "inventory-upd",
    RaidSummonStatus: "raid-summon-status",
    RaidJoinStatus: "raid-join-status",
    RaidDamaged: "raid-damaged",
    RaidFinished: "raid-finished",
    RaidNewParticipant: "raid-new-participant",
    RaidChallengeUpdate: "raid-ch-update",
    CraftingStatus: "crafting-status",
    TimerRefilled: "timer-refilled",
    ChestOpened: "chest-opened",
    ItemEnchanted: "item-enchanted",
    BuffApplied: "buff-applied",
    BuffUpdate: "buff-update",
    ItemPurchased: "item-purchased",
    TrialAttemptsPurchased: "trial-attempts-purchased",
    TowerAttemptsPurchased: "tower-attempts-purchased",
    GoldExchangeBoostPurchased: "gold-exchange-boost-purchased",
    DivTokenWithdrawal: "div-token-withdrawal",
    TournamentFinished: "tournament-finished",
    RaceFinished: "race-finished",
    UnitSummoned: "unit-summoned",
    UnitUpdated: "unit-updated",
    UnitsRemoved: "units-removed"
}
