module.exports = {
    Auth: "auth",
    ChangeNickname: "change_nickname",
    EngageQuest: "engage_quest",
    GetQuestData: "get_quest_data",
    GetUserInfo: "get_user_info",
    BuyStat: "buy_stat",
    AttackQuestBoss: "att_quest_boss",
    AttackRaidBoss: "att_raid_boss",
    ResetZone: "reset_zone",
    GetExpTable: "get_exp_table",
    EquipItem: "equip_item",
    UnequipItem: "unequip_item",
    JoinRaid: "join_raid",
    FetchRaidInfo: "fetch_raid_info",
    SummonRaid: "summon_raid",
    RefillTimer: "refill_timer",
    FetchRaidSummonList: "fetch_raid_summon",
    GetCurrencyConversionRate: "get_currency_rate"
}